name: Hasura CLI

on:
  push:
    paths:
      - hasura-cli/
  pull_request:
  workflow_dispatch:

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::$(grep -oP '^ARG HASURA_VERSION=\K.+$' hasura-cli/Dockerfile)

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          path: hasura-cli
          repository: ctison/hasura-cli
          tags: latest,${{steps.tag.outputs.VERSION}}
          add_git_labels: true
          username: ctison
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push image to Github Packages
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          path: hasura-cli
          repository: ctison/docker/hasura-cli
          tags: latest,${{steps.tag.outputs.VERSION}}
          add_git_labels: true
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
